spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8088"

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/account
    hikari:
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver


management:
  tracing:
    sampling:
      probability: 1.0

